---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: web
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
